# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KeyboardmsmCve.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(480, 135)
        Form.setCursor(QCursor(Qt.ArrowCursor))
        Form.setStyleSheet(u"QPushButton {\n"
"	border-radius: 10px;\n"
"	font: 16px \"Poppins\";\n"
"	border: 1px solid #00007f;\n"
"	background-color: white;\n"
"	color: #00007f;\n"
"}")
        self.btn33 = QPushButton(Form)
        self.btn33.setObjectName(u"btn33")
        self.btn33.setGeometry(QRect(175, 100, 178, 21))
        self.btn33.setStyleSheet(u"")
        self.btn14 = QPushButton(Form)
        self.btn14.setObjectName(u"btn14")
        self.btn14.setGeometry(QRect(151, 40, 37, 21))
        self.btn14.setStyleSheet(u"")
        self.btn19 = QPushButton(Form)
        self.btn19.setObjectName(u"btn19")
        self.btn19.setGeometry(QRect(386, 40, 37, 21))
        self.btn19.setStyleSheet(u"")
        self.btn10 = QPushButton(Form)
        self.btn10.setObjectName(u"btn10")
        self.btn10.setGeometry(QRect(433, 10, 37, 21))
        self.btn10.setStyleSheet(u"")
        self.btn32 = QPushButton(Form)
        self.btn32.setObjectName(u"btn32")
        self.btn32.setGeometry(QRect(128, 100, 37, 21))
        self.btn32.setStyleSheet(u"")
        self.btn22 = QPushButton(Form)
        self.btn22.setObjectName(u"btn22")
        self.btn22.setGeometry(QRect(81, 70, 37, 21))
        self.btn22.setStyleSheet(u"")
        self.btn3 = QPushButton(Form)
        self.btn3.setObjectName(u"btn3")
        self.btn3.setGeometry(QRect(105, 10, 37, 21))
        self.btn3.setStyleSheet(u"")
        self.btn6 = QPushButton(Form)
        self.btn6.setObjectName(u"btn6")
        self.btn6.setGeometry(QRect(245, 10, 37, 21))
        self.btn6.setStyleSheet(u"")
        self.btn29 = QPushButton(Form)
        self.btn29.setObjectName(u"btn29")
        self.btn29.setGeometry(QRect(410, 70, 63, 21))
        self.btn29.setStyleSheet(u"border-radius: 10px;\n"
"background-color: #00007f;\n"
"font: 18px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn18 = QPushButton(Form)
        self.btn18.setObjectName(u"btn18")
        self.btn18.setGeometry(QRect(339, 40, 37, 21))
        self.btn18.setStyleSheet(u"")
        self.btn27 = QPushButton(Form)
        self.btn27.setObjectName(u"btn27")
        self.btn27.setGeometry(QRect(316, 70, 37, 21))
        self.btn27.setStyleSheet(u"")
        self.btn2 = QPushButton(Form)
        self.btn2.setObjectName(u"btn2")
        self.btn2.setGeometry(QRect(57, 10, 37, 21))
        self.btn2.setStyleSheet(u"")
        self.btn20 = QPushButton(Form)
        self.btn20.setObjectName(u"btn20")
        self.btn20.setGeometry(QRect(433, 40, 41, 21))
        self.btn20.setStyleSheet(u"")
        self.btn1 = QPushButton(Form)
        self.btn1.setObjectName(u"btn1")
        self.btn1.setGeometry(QRect(10, 10, 37, 21))
        self.btn1.setStyleSheet(u"")
        self.btn9 = QPushButton(Form)
        self.btn9.setObjectName(u"btn9")
        self.btn9.setGeometry(QRect(386, 10, 37, 21))
        self.btn9.setStyleSheet(u"")
        self.btn23 = QPushButton(Form)
        self.btn23.setObjectName(u"btn23")
        self.btn23.setGeometry(QRect(128, 70, 37, 21))
        self.btn23.setStyleSheet(u"")
        self.btn35 = QPushButton(Form)
        self.btn35.setObjectName(u"btn35")
        self.btn35.setGeometry(QRect(410, 100, 63, 21))
        self.btn35.setStyleSheet(u"background-color: #00007f;\n"
"font: 32px \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.btn30 = QPushButton(Form)
        self.btn30.setObjectName(u"btn30")
        self.btn30.setGeometry(QRect(10, 100, 61, 21))
        self.btn30.setStyleSheet(u"background-color: #00007f;\n"
"color: rgb(255, 255, 255);")
        self.btn17 = QPushButton(Form)
        self.btn17.setObjectName(u"btn17")
        self.btn17.setGeometry(QRect(292, 40, 37, 21))
        self.btn17.setStyleSheet(u"")
        self.btn15 = QPushButton(Form)
        self.btn15.setObjectName(u"btn15")
        self.btn15.setGeometry(QRect(198, 40, 37, 21))
        self.btn15.setStyleSheet(u"")
        self.btn28 = QPushButton(Form)
        self.btn28.setObjectName(u"btn28")
        self.btn28.setGeometry(QRect(363, 70, 37, 21))
        self.btn28.setStyleSheet(u"")
        self.btn7 = QPushButton(Form)
        self.btn7.setObjectName(u"btn7")
        self.btn7.setGeometry(QRect(292, 10, 37, 21))
        self.btn7.setStyleSheet(u"")
        self.btn25 = QPushButton(Form)
        self.btn25.setObjectName(u"btn25")
        self.btn25.setGeometry(QRect(222, 70, 37, 21))
        self.btn25.setStyleSheet(u"")
        self.btn16 = QPushButton(Form)
        self.btn16.setObjectName(u"btn16")
        self.btn16.setGeometry(QRect(245, 40, 37, 21))
        self.btn16.setStyleSheet(u"")
        self.btn21 = QPushButton(Form)
        self.btn21.setObjectName(u"btn21")
        self.btn21.setGeometry(QRect(10, 70, 61, 21))
        self.btn21.setStyleSheet(u"background-color: #00007f;\n"
"color: rgb(255, 255, 255);")
        self.btn31 = QPushButton(Form)
        self.btn31.setObjectName(u"btn31")
        self.btn31.setGeometry(QRect(81, 100, 37, 21))
        self.btn31.setStyleSheet(u"")
        self.btn26 = QPushButton(Form)
        self.btn26.setObjectName(u"btn26")
        self.btn26.setGeometry(QRect(269, 70, 37, 21))
        self.btn26.setStyleSheet(u"")
        self.btn34 = QPushButton(Form)
        self.btn34.setObjectName(u"btn34")
        self.btn34.setGeometry(QRect(363, 100, 37, 21))
        self.btn34.setStyleSheet(u"")
        self.btn13 = QPushButton(Form)
        self.btn13.setObjectName(u"btn13")
        self.btn13.setGeometry(QRect(105, 40, 37, 21))
        self.btn13.setStyleSheet(u"")
        self.btn12 = QPushButton(Form)
        self.btn12.setObjectName(u"btn12")
        self.btn12.setGeometry(QRect(57, 40, 37, 21))
        self.btn12.setStyleSheet(u"")
        self.btn5 = QPushButton(Form)
        self.btn5.setObjectName(u"btn5")
        self.btn5.setGeometry(QRect(198, 10, 37, 21))
        self.btn5.setStyleSheet(u"")
        self.btn24 = QPushButton(Form)
        self.btn24.setObjectName(u"btn24")
        self.btn24.setGeometry(QRect(175, 70, 37, 21))
        self.btn24.setStyleSheet(u"")
        self.btn8 = QPushButton(Form)
        self.btn8.setObjectName(u"btn8")
        self.btn8.setGeometry(QRect(339, 10, 37, 21))
        self.btn8.setStyleSheet(u"")
        self.btn4 = QPushButton(Form)
        self.btn4.setObjectName(u"btn4")
        self.btn4.setGeometry(QRect(151, 10, 37, 21))
        self.btn4.setStyleSheet(u"")
        self.btn11 = QPushButton(Form)
        self.btn11.setObjectName(u"btn11")
        self.btn11.setGeometry(QRect(10, 40, 37, 21))
        self.btn11.setStyleSheet(u"")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.btn33.setText("")
        self.btn14.setText(QCoreApplication.translate("Form", u"f", None))
        self.btn19.setText(QCoreApplication.translate("Form", u"l", None))
        self.btn10.setText(QCoreApplication.translate("Form", u"p", None))
        self.btn32.setText(QCoreApplication.translate("Form", u",", None))
        self.btn22.setText(QCoreApplication.translate("Form", u"z", None))
        self.btn3.setText(QCoreApplication.translate("Form", u"e", None))
        self.btn6.setText(QCoreApplication.translate("Form", u"y", None))
        self.btn29.setText(QCoreApplication.translate("Form", u"\u232b", None))
        self.btn18.setText(QCoreApplication.translate("Form", u"k", None))
        self.btn27.setText(QCoreApplication.translate("Form", u"n", None))
        self.btn2.setText(QCoreApplication.translate("Form", u"w", None))
        self.btn20.setText(QCoreApplication.translate("Form", u"\u00f1", None))
        self.btn1.setText(QCoreApplication.translate("Form", u"q", None))
        self.btn9.setText(QCoreApplication.translate("Form", u"o", None))
        self.btn23.setText(QCoreApplication.translate("Form", u"x", None))
        self.btn35.setText(QCoreApplication.translate("Form", u"\u21e8", None))
        self.btn30.setText(QCoreApplication.translate("Form", u"?123", None))
        self.btn17.setText(QCoreApplication.translate("Form", u"j", None))
        self.btn15.setText(QCoreApplication.translate("Form", u"g", None))
        self.btn28.setText(QCoreApplication.translate("Form", u"m", None))
        self.btn7.setText(QCoreApplication.translate("Form", u"u", None))
        self.btn25.setText(QCoreApplication.translate("Form", u"v", None))
        self.btn16.setText(QCoreApplication.translate("Form", u"h", None))
        self.btn21.setText(QCoreApplication.translate("Form", u"May\u00fas", None))
        self.btn31.setText(QCoreApplication.translate("Form", u"/", None))
        self.btn26.setText(QCoreApplication.translate("Form", u"b", None))
        self.btn34.setText(QCoreApplication.translate("Form", u".", None))
        self.btn13.setText(QCoreApplication.translate("Form", u"d", None))
        self.btn12.setText(QCoreApplication.translate("Form", u"s", None))
        self.btn5.setText(QCoreApplication.translate("Form", u"t", None))
        self.btn24.setText(QCoreApplication.translate("Form", u"c", None))
        self.btn8.setText(QCoreApplication.translate("Form", u"i", None))
        self.btn4.setText(QCoreApplication.translate("Form", u"r", None))
        self.btn11.setText(QCoreApplication.translate("Form", u"a", None))
    # retranslateUi

